POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "Sample title",
  "description": "Podemos já vislumbrar o modo pelo qual a consulta aos diversos militantes assume importantes posições no estabelecimento do sistema de formação de quadros que corresponde às necessidades."
}

###

POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "Another title",
  "description": "Do mesmo modo, o desafiador cenário globalizado auxilia a preparação e a composição dos relacionamentos verticais entre as hierarquias."
}

###

POST http://localhost:3333/tasks
Content-Type: application/json

{
  "description": "Do mesmo modo, o desafiador cenário globalizado auxilia a preparação e a composição dos relacionamentos verticais entre as hierarquias."
}

###

POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "Barabara"
}
